### ISSUE TITLE
npm install fails

### ISSUE THREAD

**Issue by blazindrop** [DinoChiesa/jwt-webtool#14]
Hi, first great project. It looks very useful. Unfortunately, when I run npm install I receive an error. Is this a node version issue?

```js
jwt-webtool git:(main) ✗ npm install
npm WARN deprecated flatten@1.0.3: flatten is deprecated in favor of utility frameworks such as lodash.
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated uuid@3.3.3: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated popper.js@1.16.0: You can find the new Popper v2 at @popperjs/core, this package is dedicated to the legacy v1
npm WARN deprecated core-js@2.6.10: core-js@<3.3 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Please, upgrade your dependencies to the actual version of core-js.
npm ERR! code 1
npm ERR! path /Users/mike/git/jwt-webtool/node_modules/node-sass
npm ERR! command failed
npm ERR! command sh -c node scripts/install.js
npm ERR! /Users/mike/git/jwt-webtool/node_modules/string-width/index.js:2
npm ERR! var stripAnsi = require('strip-ansi');
npm ERR!                 ^
npm ERR!
npm ERR! Error [ERR_REQUIRE_ESM]: require() of ES Module /Users/mike/git/jwt-webtool/node_modules/strip-ansi/index.js from /Users/mike/git/jwt-webtool/node_modules/string-width/index.js not supported.
npm ERR! Instead change the require of /Users/mike/git/jwt-webtool/node_modules/strip-ansi/index.js in /Users/mike/git/jwt-webtool/node_modules/string-width/index.js to a dynamic import() which is available in all CommonJS modules.
npm ERR!     at Object.<anonymous> (/Users/mike/git/jwt-webtool/node_modules/string-width/index.js:2:17)
npm ERR!     at Object.<anonymous> (/Users/mike/git/jwt-webtool/node_modules/wide-align/align.js:2:19)
npm ERR!     at Object.<anonymous> (/Users/mike/git/jwt-webtool/node_modules/gauge/render-template.js:2:13)
npm ERR!     at Object.<anonymous> (/Users/mike/git/jwt-webtool/node_modules/gauge/plumbing.js:3:22)
npm ERR!     at Object.<anonymous> (/Users/mike/git/jwt-webtool/node_modules/gauge/index.js:2:16)
npm ERR!     at Object.<anonymous> (/Users/mike/git/jwt-webtool/node_modules/npmlog/log.js:3:13)
npm ERR!     at Object.<anonymous> (/Users/mike/git/jwt-webtool/node_modules/node-sass/scripts/install.js:9:9) {
npm ERR!   code: 'ERR_REQUIRE_ESM'
npm ERR! }
npm ERR!
npm ERR! Node.js v17.0.1

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/mike/.npm/_logs/2022-01-20T16_55_40_520Z-debug.log
```

**Comment by rangzen** [comment]
Same issue with Node 16.

**Comment by DinoChiesa** [comment]
Thanks for this feedback. 
I think I've fixed this problem in the latest commit. 
Check it out.
